In [2]:
from bs4 import BeautifulSoup
import requests,openpyxl

excel = openpyxl.Workbook()
print(excel.sheetnames)
sheet = excel.active
sheet.title = 'Top 100 Movies of all time'
print(excel.sheetnames)
sheet.append(['Movie Rank','Movie Name','Year of Release','IMDB Rating','Oscar'])

['Sheet']
['Top 100 Movies of all time']

In [3]:
source = requests.get('https://www.imdb.com/list/ls055592025/')
soup = BeautifulSoup(source.text,'html.parser')
movies = soup.find('div',class_ = 'lister-list').find_all('div',class_ = 'lister-item mode-detail')

for movie in movies:
    
    Rank = movie.find('h3', class_ = 'lister-item-header').find('span', class_ = 'lister-item-index unbold text-primary').text.strip('.')

    Name = movie.find('h3', class_ = 'lister-item-header').find('a').text
        
    Year = movie.find('h3', class_ = 'lister-item-header').find('span', class_ = 'lister-item-year text-muted unbold').text.strip('()')
    
    Rating = movie.find('div', class_ = 'ipl-rating-star small').get_text(strip = True)
    
    Oscar = movie.find('div', class_ = 'list-description').text.split()
    
    
    print(int(Rank),Name,int(Year),float(Rating),Oscar[-17])
    sheet.append([int(Rank),Name,int(Year),float(Rating),Oscar[-17]])

excel.save('IMDB Top 100 Movies.xlsx')

1 The Godfather 1972 9.2 3
2 The Shawshank Redemption 1994 9.3 0
3 Schindler's List 1993 9.0 7
4 Raging Bull 1980 8.2 2
5 Casablanca 1942 8.5 3
6 Citizen Kane 1941 8.3 1
7 Gone with the Wind 1939 8.2 8
8 The Wizard of Oz 1939 8.1 2
9 One Flew Over the Cuckoo's Nest 1975 8.7 5
10 Lawrence of Arabia 1962 8.3 7
11 Vertigo 1958 8.3 0
12 Psycho 1960 8.5 0
13 The Godfather Part II 1974 9.0 6
14 On the Waterfront 1954 8.1 8
15 Sunset Blvd. 1950 8.4 3
16 Forrest Gump 1994 8.8 6
17 The Sound of Music 1965 8.1 5
18 12 Angry Men 1957 9.0 0
19 West Side Story 1961 7.6 10
20 Star Wars 1977 8.6 6
21 2001: A Space Odyssey 1968 8.3 1
22 E.T. the Extra-Terrestrial 1982 7.9 4
23 The Silence of the Lambs 1991 8.6 5
24 Chinatown 1974 8.2 1
25 The Bridge on the River Kwai 1957 8.2 7
26 Singin' in the Rain 1952 8.3 0
27 It's a Wonderful Life 1946 8.6 0
28 Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb 1964 8.4 0
29 Some Like It Hot 1959 8.2 1
30 Ben-Hur 1959 8.1 11
31 Apocalypse Now 1979 8.5 2
32 Amadeus 1984 8.4 8
33 The Lord of the Rings: The Return of the King 2003 9.0 11
34 Gladiator 2000 8.5 5
35 Titanic 1997 7.9 11
36 From Here to Eternity 1953 7.6 8
37 Saving Private Ryan 1998 8.6 5
38 Unforgiven 1992 8.2 4
39 Raiders of the Lost Ark 1981 8.4 4
40 Rocky 1976 8.1 3
41 A Streetcar Named Desire 1951 7.9 4
42 The Philadelphia Story 1940 7.9 2
43 To Kill a Mockingbird 1962 8.3 3
44 An American in Paris 1951 7.2 6
45 The Best Years of Our Lives 1946 8.1 7
46 My Fair Lady 1964 7.8 8
47 A Clockwork Orange 1971 8.3 0
48 Doctor Zhivago 1965 7.9 5
49 The Searchers 1956 7.9 Oscar
50 Jaws 1975 8.1 3
51 Patton 1970 7.9 7
52 Butch Cassidy and the Sundance Kid 1969 8.0 4
53 The Treasure of the Sierra Madre 1948 8.2 3
54 Il buono, il brutto, il cattivo 1966 8.8 Oscar
55 The Apartment 1960 8.3 5
56 Platoon 1986 8.1 4
57 High Noon 1952 8.0 4
58 Braveheart 1995 8.4 5
59 Dances with Wolves 1990 8.0 7
60 Jurassic Park 1993 8.2 3
61 The Exorcist 1973 8.1 2
62 The Pianist 2002 8.5 3
63 Goodfellas 1990 8.7 1
64 The Deer Hunter 1978 8.1 5
65 All Quiet on the Western Front 1930 8.1 2
66 Bonnie and Clyde 1967 7.7 2
67 The French Connection 1971 7.7 5
68 City Lights 1931 8.5 0
69 It Happened One Night 1934 8.1 5
70 A Place in the Sun 1951 7.7 6
71 Midnight Cowboy 1969 7.8 3
72 Mr. Smith Goes to Washington 1939 8.1 1
73 Rain Man 1988 8.0 4
74 Annie Hall 1977 8.0 4
75 Fargo 1996 8.1 2
76 Giant 1956 7.6 1
77 Shane 1953 7.6 1
78 The Grapes of Wrath 1940 8.1 2
79 The Green Mile 1999 8.6 0
80 Close Encounters of the Third Kind 1977 7.6 1
81 Nashville 1975 7.7 1
82 Network 1976 8.1 4
83 The Graduate 1967 8.0 1
84 American Graffiti 1973 7.4 0
85 Pulp Fiction 1994 8.9 1
86 Terms of Endearment 1983 7.4 5
87 Good Will Hunting 1997 8.3 2
88 The African Queen 1951 7.7 1
89 Stagecoach 1939 7.8 2
90 Mutiny on the Bounty 1935 7.7 1
91 The Great Dictator 1940 8.4 0
92 Double Indemnity 1944 8.3 0
93 The Maltese Falcon 1941 8.0 0
94 Wuthering Heights 1939 7.5 1
95 Taxi Driver 1976 8.2 0
96 Rear Window 1954 8.5 0
97 The Third Man 1949 8.1 1
98 Rebel Without a Cause 1955 7.6 0
99 North by Northwest 1959 8.3 0
100 Yankee Doodle Dandy 1942 7.6 3